spring:
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        enabled: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:tcp://localhost/~/test
    
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      show-sql: 'true'
      format_sql: 'true'
      use_sql_comments: 'true'
      ddl-auto: create-drop
    
    database-platform: org.hibernate.dialect.H2Dialect
  devtools:
    livereload:
      enabled: 'true'
logging:
  level:
    org:
      hibernate:
        type: debug
    root: debug
